

# The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

# 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

# Let us list the factors of the first seven triangle numbers:

#      1: 1
#      3: 1,3
#      6: 1,2,3,6
#     10: 1,2,5,10
#     15: 1,3,5,15
#     21: 1,3,7,21
#     28: 1,2,4,7,14,28

# We can see that 28 is the first triangle number to have over five divisors.

# What is the value of the first triangle number to have over five hundred divisors?


import math

class prime(object):
	"""docstring for prime"""
	def __init__(self, primes=[2, ]):
		super(prime, self).__init__()
		self.primes = primes

	def currentprimes(self):
		return self.primes

	def isprime(self, n):
		if n == 2:
			return True
		elif n > 1:
			nmax = int(math.sqrt(n)+1)
			for prime in self.primes:
				if n in self.primes:
					return True
				elif prime >= nmax:
					self.primes.append(n)
					return True
				elif n % prime == 0:
					return False
		else:
			return False

	def nextprime(self, n=1):
		while True:
			n += 1
			if n > len(self.primes):
				currentnumber = self.primes[-1]+1
				while not self.isprime(currentnumber):
					currentnumber += 1
			yield self.primes[n-2]

	def giveprimes(self, n):
		"""returns list up to and including n"""
		if n > self.primes[-1]:
			for current in range(self.primes[-1], n+1):
				self.isprime(current)
		return [prime for prime in self.primes if prime <= n]


def trianglenumber(n):
	return sum(range(n+1))

def factors(n):
    """Gives list of proper divisors, excludes n"""
    counter = 1
    divisors = []
    while counter < int(n**0.5)+1:
        if n%counter == 0:
            divisors.append(counter)
            if counter != n/counter:    #remove "and test != 1" if you want to include n itself
            	# prevents entering the same number twice
            	divisors.append(n/counter)
        counter += 1
    divisors.sort()
    return divisors

def trialdivision(n):
	p = prime()
	primelist = [p for p in next(priem.nextprime()) if p**2+1 < n]
	return primelist


if __name__ == '__main__':
	# n = 1
	# triangle = trianglenumber(n)
	# l = factors(triangle)
	# while len(l) < 500:
	# 	n += 1
	# 	triangle = trianglenumber(n)
	# 	l = factors(triangle)
	# print n, triangle, l
	for n in range(10):
		print n, trialdivision(n)
