/*
Euler 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, 
the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the 
even-valued terms.
*/


#include <iostream>
#include <vector>

using namespace std;

void fibbonaci (int n, vector<int>& fib);

int main() 
{
	vector<int> fib = {1, 2};
	int sumofevenfib = 2;

	while (fib.back() < 4000000)
	{
		fibbonaci(fib.size()+1, fib);
		if (fib.back() % 2 == 0)
		{
			sumofevenfib += fib.back();
		}
	}
	cout << sumofevenfib << endl;
}

void fibbonaci (int n, vector<int>& fib)
{
	int fib1;
	int fib2;
	if (fib.size() < n)
	{
		for (int i = fib.size(); i < n; i++)
		{
			fib1 = fib.back();
			fib2 = fib[fib.size()-2];
			cout << fib1 << ' ' << fib2 << ' ' << fib1 + fib2 << endl;
			fib.emplace_back(fib1 + fib2);
		}
	}
}

